---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Premium - Accounts API
  apiPackage: Accounts
  licenseName: MIT
  UserId: SpojeNet
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: vitezslav.dvorak@spojenet.cz
  infoUrl: https://www.csas.cz/content/dam/cz/csas/www_csas_cz/dokumenty/obecne/how-to-connect-to-api-of-cs.pdf
  artifactUrl: https://github.com/Spoje-NET/php-csas-webapi
  appDescription: PHP API client for CSAS Premium Accounts WebAPI
  apiVersion: 3.0.0
  allowUnicodeIdentifiers: true
  invokerPackage: SpojeNet\CSas
  modelPackage: Model
  developerOrganization: SpojeNet
  developerOrganizationUrl: https://spojenet.cz
  variableNamingConvention: camelCase
  composerPackageName: spojenet/csas-accountsapi
files:
  composer.mustache:
      folder: .
      destinationFilename: composer.json
  gitignore.mustache:
      folder: .
      destinationFilename: .gitignore
  ApiClient.mustache:
      folder: lib
      destinationFilename: ApiClient.php
  Statementor.mustache:
      folder: lib
      destinationFilename: Statementor.php

