---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Premium - Accounts API
  apiPackage: AccountsApi
  UserId: VitexSoftware
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: vitezslav.dvorak@spojenet.cz
  infoUrl: https://github.com/Spoje-NET/php-csas-webapi
  infoDescription: PHP API client for CSAS WebAPI
  apiVersion: 3.0.0
  allowUnicodeIdentifiers: true
  artifactVersion: 0.1.0
  invokerPackage: Spoje-NET\php-csas-webapi
  modelPackage: Model
  variableNamingConvention: camelCase
