---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Premium - Accounts API
  apiPackage: AccountsApi
  licenseName: MIT
  UserId: SpojeNet
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: vitezslav.dvorak@spojenet.cz
  infoUrl: https://github.com/Spoje-NET/php-csas-webapi
  artifactUrl: https://github.com/Spoje-NET/php-csas-webapi
  appDescription: PHP API client for CSAS Premium Accounts WebAPI
  apiVersion: 3.0.0
  allowUnicodeIdentifiers: true
  invokerPackage: SpojeNET\CsasAccountsApi
  modelPackage: Model
  developerOrganization: SpojeNET
  developerOrganizationUrl: https://spojenet.cz
  variableNamingConvention: camelCase
  composerPackageName: spojenet/csas-accountsapi
  composer.mustache:
      folder: .
      destinationFilename: composer.json
