---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: Premium - Accounts API
  apiPackage: AccountsApi
  UserId: VitexSoftware
  RepoId: php-vitexsoftware-rbczpremiumapi
  infoEmail: vitezslav.dvorak@spojenet.cz
  allowUnicodeIdentifiers: true
  artifactVersion: 3.0.0
  invokerPackage: Spoje-NET\php-csas-webapi
  modelPackage: Model
  variableNamingConvention: camelCase
