<?php

declare(strict_types=1);

/**
 * This file is part of the CSasWebApi package
 *
 * https://github.com/Spoje-NET/php-csas-webapi
 *
 * (c) SpojeNetIT <http://spoje.net/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Production Accounts API V3.
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\CSas\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetAccountStatements200ResponseStatementsInnerPeriodTest Class Doc Comment.
 *
 * @category    Class
 *
 * @description GetAccountStatements200ResponseStatementsInnerPeriod
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class GetAccountStatements200ResponseStatementsInnerPeriodTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "GetAccountStatements200ResponseStatementsInnerPeriod".
     */
    public function testGetAccountStatements200ResponseStatementsInnerPeriod(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateFrom".
     */
    public function testPropertyDateFrom(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateTo".
     */
    public function testPropertyDateTo(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
