<?php

declare(strict_types=1);

/**
 * This file is part of the CsasWebApi package
 *
 * https://github.com/Spoje-NET/php-csas-webapi
 *
 * (c) SpojeNetIT <http://spoje.net/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Production Accounts API V3.
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\Csas\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetailsTest Class Doc Comment.
 *
 * @category    Class
 *
 * @description GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails
 *
 * @author      OpenAPI Generator team
 *
 * @see        https://openapi-generator.tech
 */
class GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetailsTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case.
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test "GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails".
     */
    public function testGetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "references".
     */
    public function testPropertyReferences(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amountDetails".
     */
    public function testPropertyAmountDetails(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relatedParties".
     */
    public function testPropertyRelatedParties(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relatedAgents".
     */
    public function testPropertyRelatedAgents(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remittanceInformation".
     */
    public function testPropertyRemittanceInformation(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTransactionInformation".
     */
    public function testPropertyAdditionalTransactionInformation(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalRemittanceInformation".
     */
    public function testPropertyAdditionalRemittanceInformation(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTransactionDescription".
     */
    public function testPropertyAdditionalTransactionDescription(): void
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
