<?php
/**
 * GetTransactions200ResponseTransactionsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpojeNET\CSas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Production Accounts API V3
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\CSas\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetTransactions200ResponseTransactionsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetTransactions200ResponseTransactionsInner
 * @package     SpojeNET\CSas
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetTransactions200ResponseTransactionsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetTransactions200ResponseTransactionsInner"
     */
    public function testGetTransactions200ResponseTransactionsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entryReference"
     */
    public function testPropertyEntryReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "creditDebitIndicator"
     */
    public function testPropertyCreditDebitIndicator()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bookingDate"
     */
    public function testPropertyBookingDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valueDate"
     */
    public function testPropertyValueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bankTransactionCode"
     */
    public function testPropertyBankTransactionCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entryDetails"
     */
    public function testPropertyEntryDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
