<?php
/**
 * GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetailsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpojeNET\Csas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Production Accounts API V3
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\Csas\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails
 * @package     SpojeNET\Csas
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails"
     */
    public function testGetTransactions200ResponseTransactionsInnerEntryDetailsTransactionDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "references"
     */
    public function testPropertyReferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amountDetails"
     */
    public function testPropertyAmountDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relatedParties"
     */
    public function testPropertyRelatedParties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relatedAgents"
     */
    public function testPropertyRelatedAgents()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remittanceInformation"
     */
    public function testPropertyRemittanceInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTransactionInformation"
     */
    public function testPropertyAdditionalTransactionInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalRemittanceInformation"
     */
    public function testPropertyAdditionalRemittanceInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additionalTransactionDescription"
     */
    public function testPropertyAdditionalTransactionDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
