<?php
/**
 * MyAccountsGet500ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpojeNET\\CsasWebApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Production Accounts API V3
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\\CsasWebApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MyAccountsGet500ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description MyAccountsGet500Response
 * @package     SpojeNET\\CsasWebApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MyAccountsGet500ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MyAccountsGet500Response"
     */
    public function testMyAccountsGet500Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "errorCode"
     */
    public function testPropertyErrorCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
