<?php
/**
 * StatementListAccountStatementsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SpojeNET\CSas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Production Accounts API V3
 *
 * API for managing production accounts.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vitezslav.dvorak@spojenet.cz
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SpojeNET\CSas\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StatementListAccountStatementsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description StatementListAccountStatementsInner
 * @package     SpojeNET\CSas
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StatementListAccountStatementsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StatementListAccountStatementsInner"
     */
    public function testStatementListAccountStatementsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accountStatementId"
     */
    public function testPropertyAccountStatementId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "month"
     */
    public function testPropertyMonth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sequenceNumber"
     */
    public function testPropertySequenceNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "formats"
     */
    public function testPropertyFormats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
